spring:
    datasource:
        url: jdbc:h2:mem:student-service
    h2:
        console:
            enabled: true    
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            rate: 10
            probability: 1
server:
    port: 3001
