spring:
    datasource:
        url: jdbc:h2:mem:course-service
    h2:
        console:
            enabled: true    
    config:
        import: configserver:http://localhost:5002
server:
    port: 3000